### PR TITLE
(maint) fix typo in indirector docs (van->and)

### PR DESCRIPTION
**Pull request by johnmccabe**

### CODE REVIEW

**Comment by jtappa** [comment]
🙊  wow, that's been there a while. Thanks for the fix! 🎉

**Comment by nfagerlund** [comment]
@jtappa Heyyyyyyyyyyyyyyyy, this file is auto-generated, so that typo will return from the dead the minute we generate new docs. (It's already in the 4.8 stuff, right?) 

Would you like to handle the PR to core? The file is `lib/puppet/reference/indirection.rb`.

**Comment by johnmccabe** [comment]
@nfagerlund / @jtappa I'll raise this against core now, thx for the heads up

**Comment by jtappa** [comment]
@nfagerlund oh dang, I wasn't even looking at what directory this page was. 😿  Sorry!

**Pull request merged**
