### PR TITLE
Add Wily, Xenial, and F23 PC1 docs.

### PR DESCRIPTION
**Pull request by gguillotte**

### CODE REVIEW

**Comment by nfagerlund** [comment]
Is this waiting for anything, or should we just merge it?

**Comment by gguillotte** [comment]
I'm not waiting on anything for this.

**Comment by nfagerlund** [comment]
Cool. Ok, so I notice the f23 snippet is not actually included anywhere; is that on purpose? Likewise with dropping 15.04; is it EOLed?

**Comment by gguillotte** [comment]
Per @stahnma in [DOCUMENT-552](https://tickets.puppetlabs.com/DOCUMENT-552), we no longer provide packages for 15.04. The packages in apt.puppetlabs.com confirm this.

We shipped F23 puppet-agent packages from 1.4 onward, but I'd like some confirmation before including it in docs.

Per DOCUMENT-552, it sounds like we also need to remove Debian 6/Squeeze and Fedora 21.

**Comment by gguillotte** [comment]
Revised to address DOCUMENT-552.

**Comment by gguillotte** [comment]
@nfagerlund FYI I'm still not waiting on anything here.

**Comment by nfagerlund** [comment]
IDK why I dropped the ball on this so long. Sorry, merging!

**Pull request merged**
