### PR TITLE
(PUP-7579) Update RegEx for Tag

### PR DESCRIPTION
**Pull request by Iristyle**
- Update regular expression for tags to coincide with code changes
   made in https://github.com/puppetlabs/puppet/commit/2ac4dc0

### CODE REVIEW

**Comment by Iristyle** [comment]
@hlindberg looks like we have a few other places that could use regex updates in this doc.

@jtappa is this the right spot for this Puppet 5 PR?

**Comment by jtappa** [comment]
Yup, this is exactly it for Puppet 5 docs. Is this the first version this regex applies to? Might want to make a note so people are aware of it.

**Comment by jtappa** [comment]
Hey @Iristyle, can you please answer my question above? If it is true, I can add the note after merge, I just want to know if this needs a call out to users.

**Comment by Iristyle** [comment]
@jtappa this is the first version of Puppet to apply this expanded regular expression, yes.  It might be useful to call that out here *unless* our blanket statement is "you must use Puppet on this version for broad UTF-8 support" and that's covered elsewhere.

**Pull request merged**
