### PR TITLE
(DOC-3177) run stages are parse order dependent

### PR DESCRIPTION
**Pull request by binford2k**

### CODE REVIEW

**Comment by jtappa** [comment]
Hey @hlindberg, does this look technically accurate to you? If so we can merge and bring forward to latest docs.

**Comment by hlindberg** [comment]
We prefer the terms "evaluation-order dependant" and "evaluation order" over the older (and inaccurate) "parse-order dependant" and "parse order". (Technically this has nothing to do with parsing)

**Comment by hlindberg** [comment]
I can not say anything about the accuracy of the change otherwise - I don't understand run-stages. (I also do not understand what the description is telling me other than I have to be careful with ordering).

**Comment by hlindberg** [comment]
@branan does this make sense to you?

**Comment by branan** [comment]
I'm with Henrik that we want evaluation-order in the docs, rather than parse-order. Otherwise this looks correct to me. I had to read it a couple of times to be sure it was right, though. It could probably be written more clearly. Perhaps just trim everything after "... that uses them"?

**Comment by jbondpdx** [comment]
@binford2k could you update your PR, in line with what @hlindberg and @branan said?

**Comment by binford2k** [comment]
@jbondpdx 👍

**Pull request merged**
