### PR TITLE
Add note about psuedo namevar

### PR DESCRIPTION
**Pull request by binford2k**
This was briefly debated in the `puppet-lint` triage today. We did not
come to a consensus. Don't merge without other approval.

### CODE REVIEW

**Comment by binford2k** [comment]
Looks like you can only request a review from members of the org. @rodjek and @rnelson0, do you have opinions on this?

**Comment by rodjek** [comment]
After thinking about this further, I'm generally against this exception. Even though the parameter is defaulting to a required value, the parameter itself is still optional as you don't have to manually specify it in your manifest/hieradata/etc.

**Comment by rodjek** [comment]
> Looks like you can only request a review from members of the org.

I should be an org member now ;)

**Comment by rnelson0** [comment]
I, too, am against an exception. It may be worth spelling out the use case AND noting that it goes with the other optionals, though.

**Comment by rodjek** [comment]
Seems like we have a unanimous decision here, so I'm going to close the puppet-lint issue that triggered this.

I agree with @rnelson0 that we should probably call out in the style guide that using a required value like `$name` or `$title` as the default value for a parameter doesn't make that parameter required. @binford2k seeing as you opened the PR, would you mind updating your change to reflect this? :)

**Pull request merged**
