### PR TITLE
Backport repo and package verification guide removal work

### PR DESCRIPTION
**Pull request by gguillotte**
-   Add PC1 includes for Puppet 4.1-4.3.
-   Add a `puppet_repositories` doc for Puppet 3.8 and port the guide content to it.
-   Update links to these guides across the docs to point to the relevant 3.8 or /latest versions.
-   Remove information about nightlies from parts of the 3.8 docs. We no longer publish 3.8 nightlies.

### CODE REVIEW

**Comment by gguillotte** [comment]
My text editor stripped some trailing spaces from docs while editing, so there are some modified lines that have no other changes.

**Comment by jtappa** [comment]
Are we waiting on anything for this to be merged?

**Comment by nfagerlund** [comment]
No, I think I meant to merge this last week and dropped the ball.

I'll take the briefest of looks now, and then hit go.

**Comment by nfagerlund** [comment]
going for it

**Pull request merged**
