### PR TITLE
(maint) Tweak how some OpenBSD user provider features are set

### PR DESCRIPTION
**Pull request by jasperla**
Original discussion here: puppetlabs/puppet#3911

### CODE REVIEW

**Comment by jasperla** [comment]
Note that I tried to run `rake build` but failed:

```
Updating puppetserver_2.0
HEAD is now at 3f53528... Merge pull request #526 from nwolfe/bug/master/fix-namespace-renaming-misses
Making new working directory for pe3.7
Not a git repository: "git@github_com_puppetlabs_pe-docs-private_git"
rake aborted!
Errno::ENOENT: No such file or directory - pe3.7
```

**Comment by nfagerlund** [comment]
Aaaaaa sorry I didn't catch this when it came in. Merging now, and I'll manually edit the existing 4.1 references.

**Comment by nfagerlund** [comment]
As for the rake build thing... yeah, I broke that for people outside the company. :/ Gotta fix it eventually.

**Comment by jasperla** [comment]
Thanks!

**Pull request merged**
