### PR TITLE
Update release notes page for 3.8

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by kylog** [comment]
@nfagerlund someone pointed this omission out on puppet-dev.

**Comment by nfagerlund** [comment]
oh, ha, 4.0 and 4.1 are missing too! I'll add those.

**Comment by nfagerlund** [comment]
bluh, let's stop manually maintaining this page sometime soon. >:P

**Comment by kylog** [comment]
Yeah .... this should be automated :)

Thanks!

**Pull request merged**
